version: "3.7"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://host.docker.internal:3100/loki/api/v1/push"

networks:
  loki:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=14d'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.wal-compression'
      - '--storage.tsdb.max-block-duration=4h'
      - '--storage.tsdb.wal-segment-size=60MB'
      - '--storage.tsdb.allow-overlapping-blocks'
      - '--query.max-samples=5000000'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - loki
  
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/config.yml
    ports:
      - "9093:9093"
    command: 
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      - loki 

  loki:
    image: grafana/loki:2.0.0-amd64
    container_name: loki
    volumes:
      - ${PWD}/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki-rules/edge/loki-rule.yaml:/etc/loki/rules/edge/loki-rule.yaml
    ports:
      - "3100:3100"
    depends_on:
      - alertmanager
    entrypoint:
     - /usr/bin/loki
     - -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/plugins/56b3f5cc33ededc11c3f540aebe00d463e122c5e5713c5652f777794c5ba631e/rootfs/var/log/docker/:/var/lib/docker/containers/1:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers/2:ro
      - ${PWD}/promtail/promtail.yaml:/etc/promtail/promtail.yml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-pipeline-stages: |
          - regex:
              expression: '(level|lvl|severity)=(?P<luvel>\w+)'
          - labels:
              luvel:
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - loki
    ports:
      - "3000:3000"
    networks:
      - loki

volumes:
  prometheus-data: {}
